version: 2.1
workflows:
  version: 2
  build_push_test:
    jobs:
      - pantheon/push
      - backup_test_env   
orbs:
  pantheon: pantheon-systems/pantheon@0.2.0 
jobs:
  backup_test_env:
    docker:
    - image: quay.io/pantheon-public/build-tools-ci:5.x
    steps:
    - run:
        name: Authenticate with Pantheon's CLI using a machine token
        command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
    - run: echo ${CIRCLE_PULL_REQUEST##*/};
    - run: echo $CI_PULL_REQUEST;