version: 2.1
workflows:
  version: 2
  build_push_test:
    jobs:
      - check_env_vars
      - pantheon/push
orbs:
  pantheon: pantheon-systems/pantheon@0.2.0
jobs:
  check_env_vars:
    docker:
    - image: quay.io/pantheon-public/build-tools-ci:5.x
    steps:
      - run:
        name: Check for enviornment variables from github
        command: echo ${CIRCLE_PULL_REQUEST##*/}